myBlogProject/entry/urls.py
from django.conf.urls import url
from entry.views import entry


app_name = 'entryApp'

urlpatterns = [
    url(r'^$',entry,name='entry'),
]

myBlogProject/myBlogProject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from entry.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home,name='home'),
    url(r'^entry/',include('entry.urls')),
]

myBlogProject/entry/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Entries(models.Model):
    name = models.CharField(max_length=64)
    topic = models.CharField(max_length=55)
    content = models.TextField(max_length=700)


    def __str__(self):
        return self.name + ' ' + self.topic

myBlogProject/entry/forms.py
from entry.models import Entries
from django import forms


class EntryForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea)
    class Meta():
        model = Entries
        fields = "__all__"

myBlogProject/entry/views.py
from django.shortcuts import render
from entry.models import Entries
from entry import forms

# Create your views here.

def home(request):
    stories = Entries.objects.order_by('name')
    con = {'var_stories':stories}
    return render(request,'home/stories.html',con)

def entry(request):
    entryForm = forms.EntryForm()
    con = {'var_entry':entryForm}

    if request.method == "POST":
        entryForm = forms.EntryForm(request.POST)

        if entryForm.is_valid():
            entryForm.save()

    return render(request,'entry/entry.html',con)

myBlogProject/templates/base/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock%}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>

<div class="container">
    <div class="jumbotron">
    <h2>Simile Blog</h2>
     <img src="{% static 'images/icon.png'%}" alt="Logo" width="100" height="100" align="right">
    </div>
    {% block body %}
    {% endblock %}

</div>
</body>
</html>

myBlogProject/templates/entry/entry.html
{% extends 'base/index.html' %}

{% block title %}entrypage{% endblock%}

{% block body %}
    <h3>Share your story Dude</h3>
    <form method="post">
        {{ var_entry.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="add">
    </form>
    <br>
    <form method="get" action="{% url 'home' %}">
        <input type="submit" class="btn btn-primary" value="Home">
    </form>
{% endblock %}

myBlogProject/templates/home/stories.html
{% extends "base/index.html" %}

{% block title %}homepage{% endblock%}

{% block body %}
    <form action="{% url 'entryApp:entry'%}" method="get">
        <input type="submit" class="btn btn-primary" value="create">
    </form>

{% if var_stories %}
    <ol type="1">
    {% for story in var_stories %}
    <li>
        <ul>
            <li>Name: {{ story.name }}</li>
            <li>Topic: {{ story.topic }}</li>
            <li>Story: {{ story.content }}</li>
            <br>
        </ul>
     </li>
    {% endfor%}
    </ol>
{% else %}
    <p>No stories yet homie! click create to add one.</p>
{% endif%}

{% endblock %}